### ISSUE TITLE
path to pdf: undefined

### ISSUE THREAD

**Issue by andrewnorell** [isleofcode/ember-render-vendor#5]
Hi @anulman, thanks for making ember-render-vendor and providing it for others to use! 
I walked through the documentation steps to integrate e-r-v into my ember app, using the same `renderers/invoice` examples provided just to see if I could get it to work, and the `renderPdf` action is outputting `path to pdf: undefined` to the console. I'm not seeing any errors.
Any idea what I may be doing wrong?

Thanks!

**Comment by anulman** [comment]
Thanks for the issue report @andrewnorell. In reviewing, I found one docs issue to fix (the renderer call should include a `{ format: 'pdf' }` in the options object passed to `this._super`), but that wouldn't lead to the `undefined` you're seeing.

Will try and repro this evening; in the interim, can you confirm that A) you're using e-r-v in an electron shell (i.e. via `ember electron`); and B) what version of e-electron you're using?

**Comment by andrewnorell** [comment]
Thanks for the response! I'm using version 2.6.0 of ember-electron. 
Ah, that's where I was went wrong. I wasn't running my Ember app via `ember electron`. Sorry for my oversight on that one. :)

**Comment by anulman** [comment]
@andrewnorell Updated the README with the 0.2.x series—now with Headless Chrome!

Closing this issue, as it seems your item is resolved + README is now up to date 👍
